"""agregar tabla sorteo

Revision ID: 077943316377
Revises: ac4246c46ff0
Create Date: 2026-07-09 01:00:49.751287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '077943316377'
down_revision = 'ac4246c46ff0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sorteo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=4), nullable=False),
    sa.Column('etiqueta', sa.String(length=80), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('registrado_por_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['registrado_por_id'], ['vendedor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sorteo')
    # ### end Alembic commands ###
