"""agregar configuracion de rifa (fecha proximo sorteo)

Revision ID: 487ceb6cc3fa
Revises: b7bbecb5b54c
Create Date: 2026-07-09 13:54:49.419618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '487ceb6cc3fa'
down_revision = 'b7bbecb5b54c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracion_rifa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_proximo_sorteo', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configuracion_rifa')
    # ### end Alembic commands ###
