"""fechas de sorteo por premio en vez de una general

Revision ID: 6b5a82e523dd
Revises: 487ceb6cc3fa
Create Date: 2026-07-09 15:19:03.783670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b5a82e523dd'
down_revision = '487ceb6cc3fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracion_rifa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_premio1', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('fecha_premio2', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('fecha_premio3', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('fecha_premio4', sa.DateTime(), nullable=True))
        batch_op.drop_column('fecha_proximo_sorteo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracion_rifa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_proximo_sorteo', sa.DATETIME(), nullable=True))
        batch_op.drop_column('fecha_premio4')
        batch_op.drop_column('fecha_premio3')
        batch_op.drop_column('fecha_premio2')
        batch_op.drop_column('fecha_premio1')

    # ### end Alembic commands ###
