"""esquema inicial

Revision ID: ac4246c46ff0
Revises: 
Create Date: 2026-07-08 23:53:29.782908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac4246c46ff0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('boleta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendedor_id', sa.Integer(), nullable=False),
    sa.Column('nombre_cliente', sa.String(length=150), nullable=False),
    sa.Column('documento', sa.String(length=30), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vendedor_id'], ['vendedor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('numero_asignado',
    sa.Column('numero', sa.String(length=4), nullable=False),
    sa.Column('boleta_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['boleta_id'], ['boleta.id'], ),
    sa.PrimaryKeyConstraint('numero')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('numero_asignado')
    op.drop_table('boleta')
    op.drop_table('vendedor')
    # ### end Alembic commands ###
