"""auditoria de pagos y anulacion de boletas

Revision ID: e96c7d6c4ce6
Revises: ea2dfceebef6
Create Date: 2026-07-15 10:49:18.036550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e96c7d6c4ce6'
down_revision = 'ea2dfceebef6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historial_pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('boleta_id', sa.Integer(), nullable=False),
    sa.Column('numero_premio', sa.Integer(), nullable=False),
    sa.Column('marcado', sa.Boolean(), nullable=False),
    sa.Column('vendedor_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['boleta_id'], ['boleta.id'], ),
    sa.ForeignKeyConstraint(['vendedor_id'], ['vendedor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('boleta', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('anulada', sa.Boolean(), nullable=False, server_default=sa.text('false'))
        )
        batch_op.add_column(sa.Column('fecha_anulacion', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('anulada_por_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('numeros_anulados', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key('fk_boleta_anulada_por', 'vendedor', ['anulada_por_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boleta', schema=None) as batch_op:
        batch_op.drop_constraint('fk_boleta_anulada_por', type_='foreignkey')
        batch_op.drop_column('numeros_anulados')
        batch_op.drop_column('anulada_por_id')
        batch_op.drop_column('fecha_anulacion')
        batch_op.drop_column('anulada')

    op.drop_table('historial_pago')
    # ### end Alembic commands ###
