"""agregar telefono al vendedor

Revision ID: ea2dfceebef6
Revises: 6b5a82e523dd
Create Date: 2026-07-09 15:47:20.921268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea2dfceebef6'
down_revision = '6b5a82e523dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendedor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefono', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendedor', schema=None) as batch_op:
        batch_op.drop_column('telefono')

    # ### end Alembic commands ###
